# Generated by Django 4.2.1 on 2023-07-03 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarNote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
