# Generated by Django 4.2.1 on 2023-07-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarNote', '0002_alter_note_visible_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='visible_to',
        ),
    ]
