# Generated by Django 4.2.1 on 2023-07-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarNote', '0004_alter_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
